# Generated by Django 6.0.7 on 2026-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_label', models.CharField(max_length=255)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('pickup_label', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('dropoff_label', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('current_cycle_used', models.FloatField()),
                ('total_miles', models.FloatField(default=0)),
                ('total_drive_hours', models.FloatField(default=0)),
                ('total_days', models.IntegerField(default=0)),
                ('route_geometry', models.JSONField(default=list)),
                ('stops', models.JSONField(default=list)),
                ('daily_logs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
